In [1]:
import numpy as np

data = np.random.randn(1000)

mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
variance = np.var(data)

lower_bound = mean - 2 * std_dev
upper_bound = mean + 2 * std_dev
outliers = data[(data < lower_bound) | (data > upper_bound)]

matrix = data[:16].reshape(4, 4)
transposed_matrix = matrix.T

print("=== Basic Statistics ===")
print(f"Mean: {mean:.2f}")
print(f"Median: {median:.2f}")
print(f"Standard Deviation: {std_dev:.2f}")
print(f"Variance: {variance:.2f}")

print("\n=== Outliers ===")
print(outliers)

print("\n=== Reshaped Matrix ===")
print(matrix)

print("\n=== Transposed Matrix ===")
print(transposed_matrix)


=== Basic Statistics ===
Mean: -0.01
Median: -0.01
Standard Deviation: 0.98
Variance: 0.96

=== Outliers ===
[ 1.95001738 -2.23120853  2.11331833 -2.15320081  3.40690821 -2.26857429
 -2.16000127  2.27762458 -2.4427391  -2.67964017  2.14597099 -2.04553423
 -1.98399562 -3.42899347 -2.56792539  1.98050509 -3.70496992  2.16543629
 -2.31270659  2.18593678  2.14005307  1.97525966  2.22959124  2.63065331
 -2.25817871  2.0638398   2.31886529  2.7905636  -2.08331811  2.15370032
 -2.22117658 -2.21501949 -2.10491208 -2.44799157 -2.58771672  2.10237962
  2.23355803  2.02545213  2.44984972  2.46750875  2.11823022 -2.18513625
 -2.23484858  2.40254366  1.99435297 -1.99355885  2.25978078]

=== Reshaped Matrix ===
[[-1.63486071 -0.76254321 -0.08792742 -1.49940954]
 [ 1.030453   -0.03428583 -0.84121661  1.09457114]
 [ 0.0333697  -1.17014972  0.93625198  0.0578266 ]
 [ 0.2405355  -0.37926099  0.34521191 -0.35112124]]

=== Transposed Matrix ===
[[-1.63486071  1.030453    0.0333697   0.2405355 ]
 [-0.76254

In [2]:
import numpy as np

array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print("Original Array:")
print(array)

slice1 = array[:2, :2]
print("\nFirst two rows and columns:")
print(slice1)

slice2 = array[2:, 2:]
print("\nLast two rows and columns:")
print(slice2)

single_row = array[1, :]
print("\nSecond row:")
print(single_row)

single_column = array[:, 2]
print("\nThird column:")
print(single_column)

step_slice = array[::2, ::2]
print("\nEvery other element (row and column):")
print(step_slice)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

First two rows and columns:
[[1 2]
 [5 6]]

Last two rows and columns:
[[11 12]
 [15 16]]

Second row:
[5 6 7 8]

Third column:
[ 3  7 11 15]

Every other element (row and column):
[[ 1  3]
 [ 9 11]]


In [3]:
import numpy as np

array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

print("Array 1:", array1)
print("Array 2:", array2)

add_result = array1 + array2
print("\nAddition:", add_result)

sub_result = array1 - array2
print("Subtraction:", sub_result)

mul_result = array1 * array2
print("Multiplication:", mul_result)

div_result = array1 / array2
print("Division:", div_result)

exp_result = np.power(array1, 2)
print("Exponentiation (Array 1 squared):", exp_result)

sqrt_result = np.sqrt(array2)
print("Square Root (Array 2):", sqrt_result)

sum_result = np.sum(array1)
print("Sum of elements in Array 1:", sum_result)

mean_result = np.mean(array2)
print("Mean of elements in Array 2:", mean_result)

dot_product = np.dot(array1, array2)
print("Dot Product:", dot_product)


Array 1: [1 2 3 4]
Array 2: [5 6 7 8]

Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]
Exponentiation (Array 1 squared): [ 1  4  9 16]
Square Root (Array 2): [2.23606798 2.44948974 2.64575131 2.82842712]
Sum of elements in Array 1: 10
Mean of elements in Array 2: 6.5
Dot Product: 70


In [4]:
import numpy as np

array = np.array([10, 20, 30, 40, 50, 30, 20, 10])

print("Array:", array)

value_to_find = 30
indices = np.where(array == value_to_find)
print(f"\nIndices of value {value_to_find}:", indices[0])

threshold = 25
greater_than_threshold = np.where(array > threshold)
print(f"\nIndices of values greater than {threshold}:", greater_than_threshold[0])

value_exists = 40 in array
print(f"\nDoes value 40 exist in the array? {value_exists}")

first_occurrence = np.where(array == value_to_find)[0][0] if value_to_find in array else None
print(f"\nFirst occurrence of value {value_to_find}: {first_occurrence}")


Array: [10 20 30 40 50 30 20 10]

Indices of value 30: [2 5]

Indices of values greater than 25: [2 3 4 5]

Does value 40 exist in the array? True

First occurrence of value 30: 2


In [5]:
import numpy as np

array = np.array([50, 20, 10, 40, 30])

print("Original Array:", array)

sorted_array = np.sort(array)
print("\nSorted Array (Ascending):", sorted_array)

sorted_array_desc = np.sort(array)[::-1]
print("Sorted Array (Descending):", sorted_array_desc)

indices = np.argsort(array)
print("\nIndices of Sorted Elements (Ascending):", indices)

sorted_rows = np.array([
    [3, 2, 1],
    [9, 8, 7],
    [6, 5, 4]
])
sorted_by_row = np.sort(sorted_rows, axis=1)
print("\nSorted by Rows (Row-wise):\n", sorted_by_row)


Original Array: [50 20 10 40 30]

Sorted Array (Ascending): [10 20 30 40 50]
Sorted Array (Descending): [50 40 30 20 10]

Indices of Sorted Elements (Ascending): [2 1 4 3 0]

Sorted by Rows (Row-wise):
 [[1 2 3]
 [7 8 9]
 [4 5 6]]
